- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
- PostKit/PostKit/Model/DailyModel.swift
- PostKit/PostKit/Model/MenuModel.swift
- PostKit/PostKit/Protocol/DailyProtocol.swift
- PostKit/PostKit/Protocol/MenuProtocol.swift
- PostKit/PostKit/Protocol/StoreProtocol.swift
`1. 각 뷰에 Extension Protocol 파일 추가 `
> [Data/#1] Add CoreData PRUD Protocol File 

- .gitignore
- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/Model/ChatGptModel.swift
- PostKit/PostKit/View/MenuView.swift
- PostKit/PostKit/ViewModel/ChatGptService.swift
close #3 
* 온보딩 페이지가 머지되면 가게 이름과 톤 변수 설정 다시 해놓겠습니다.
chat gpt 문서는 다음 [사이트](https://platform.openai.com/docs/api-reference/introduction)를 확인 부탁드립니다.
> [Feat/#3] Chat Gpt API 연결

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/Assets.xcassets/Main.colorset/Contents.json
- PostKit/PostKit/Assets.xcassets/Sub.colorset/Contents.json
- PostKit/PostKit/View/Component/CustomBtn.swift
- PostKit/PostKit/View/ResultView.swift
- 컬러 에셋 변경 (Primary -> Main, Secondary -> Sub)
- CustomBtn 컬러 에셋 적용
- ResultView UI
- 카피 생성 결과 클립 보드에 복사 및 토스트 메세지
- 완료 버튼 클릭시 메인 페이지
> [feat/#11] Add ResultView

- PostKit/PostKit/View/Component/CustomTextfield.swift
- PostKit/PostKit/View/Component/Keywords.swift
- PostKit/PostKit/View/MenuView.swift
MenuView UI수정
Button 활성화 설정
Keyboard 화면 클릭하면 사라지는 기능 추가
> [Feat/#8] add Menu View

- PostKit/PostKit/View/MenuView.swift
> [Fix/#17] Fix error in MenuView

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/Model/ToneModel.swift
- PostKit/PostKit/View/Component/CustomHeader.swift
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
- PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
- PostKit/PostKit/View/Onboarding/OnboardingRouter.swift
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
- PostKit/PostKit/View/Setting/SettingToneView.swift
closed #20
```
git 누락파일 추가
```
```
다시 복붙해서 올렸어요 ㅠㅠ
```
> [Fix/#20] 깃 누락파일 추가

- PostKit/PostKit/View/DailyView.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/MenuView.swift
- PostKit/PostKit/View/ResultView.swift
close #31
일상 페이지에 Chat Gpt 에 글 생성을 요구하는 sendMessage 함수 추가
``` swift
func sendMessage(){
Task{
var pointText = ""
if !weatherSelected.isEmpty {
pointText = pointText + "오늘 날씨의 특징으로는 "
for index in weatherSelected.indices {
pointText = pointText + "\(weatherSelected[index]), "
}
pointText = pointText + "이 있어."
}
if !dailyCoffeeSelected.isEmpty {
pointText = pointText + "오늘 이야기하고자 하는 음료는 "
for index in dailyCoffeeSelected.indices {
pointText = pointText + "\(dailyCoffeeSelected[index]), "
}
pointText = pointText + "이 있어."
}
if !dailyDessertSelected.isEmpty {
pointText = pointText + "오늘 이야기하고자 하는 디저트는 "
for index in dailyDessertSelected.indices {
pointText = pointText + "\(dailyDessertSelected[index]), "
}
pointText = pointText + "이 있어."
}
self.currentInput = "카페 일상과 관련된 인스타그램 피드를 작성해줘. …
```
> [Feat] - 일상 화면에 ChatGpt API 연결

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
> [Fix] Git conflict error 해결

- PostKit/PostKit.xcodeproj/project.pbxproj
> [Fix/#34] Fix error

- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
> [Fix] Fix error

- PostKit/PostKit/View/DailyView.swift
- PostKit/PostKit/View/MenuView.swift
- PostKit/PostKit/View/ResultView.swift
close #41 
``` swift
self.messages.append(
Message(id: UUID(), role: .system, 
content: "너는 \(appstorageManager.cafeName == "" ? "카페": appstorageManager.cafeName)를 운영하고 있으며 \(appstorageManager.cafeTone == "기본" ? "평범한" : appstorageManager.cafeTone) 말투를 가지고 있어. 글은 존댓말로 작성해줘. 글은 600자 정도로 작성해줘."))
```
> [Feat/#41] Apply AppStorage in prompt

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/DailyView.swift
- PostKit/PostKit/View/LoadingView.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/MenuView.swift
- PostKit/PostKit/View/ResultView.swift
> [Feat/#45] LoadingView 연결

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/DailyView.swift
- PostKit/PostKit/View/LoadingView.swift
- PostKit/PostKit/View/MenuView.swift
closed #43
```swift
ProgressView()
.controlSize(.extraLarge)
.padding(.bottom, 46)
```
```
```
컴포넌트를 사용해서 UI가 살짝 다른데 따로 애니메이션을 구현해야 한다면 말씀해 주세요.
> [feat] - 로딩 뷰 구현

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Component/CustomBtn.swift
- PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
- PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
- PostKit/PostKit/View/Setting/SettingView.swift
> Rash chore/#48

- PostKit/PostKit/View/Component/CustomHeader.swift
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/DailyView.swift
- PostKit/PostKit/View/LoadingView.swift
- PostKit/PostKit/View/MenuView.swift
- PostKit/PostKit/View/ResultView.swift
close #47 
- fill, stroke 동시에 적용하기
(https://www.swiftbysundell.com/articles/stroking-and-filling-a-swiftui-shape-at-the-same-time/)
> [Design/#47] Header & Tone UI 수정

- PostKit/PostKit/View/ResultView.swift
#52 
ResultView에서 답변이 길 경우, scroll 가능하도록 수정
``` swift
ScrollView{
Text(viewModel.promptAnswer)
.lineLimit(nil)
.multilineTextAlignment(.leading)
.font(.body1Bold())
.foregroundStyle(Color.gray5)
}
```
> [Chore/#52] Add scroll in result view

- PostKit/PostKit/View/Component/CustomTextfield.swift
- PostKit/PostKit/View/DailyView.swift
- PostKit/PostKit/View/MenuView.swift
> [Fix] Daily, Menu View UI 디테일 수정

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/PostKitApp.swift
- PostKit/PostKit/Protocol/SettingProtocol.swift
- PostKit/PostKit/Protocol/StoreProtocol.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
- PostKit/PostKit/View/Setting/SettingToneView.swift
- PostKit/PostKit/View/Setting/SettingView.swift
#64
```SettingView CRUD 추가```
```코드가 좀 더럽습니다. ㅠ```
```
|기능|스크린샷|
[GIF]<img src = "" width="250">|
```
SettingView 변수들의 변화가 있습니다. 개발자분들은 자세하게 확인 부탁 드립니다.
> [Data/#64] Now SettingView connected CoreData

- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Component/CustomTextfield.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/ViewModel/ChatGptService.swift
<!-- 관련있는 이슈 번호(#000)을 적어주세요.
#85
> [Fix/#85] prompt변경 및 모델 변경

- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
#90 
기존의 fullscreen cover를 Zstack으로 관리해서 사용자가 더 보기 쉽게 구조를 변경했습니다.
```
var body: some View {
ZStack {
if isFirstLaunching == true {
OnboardingView( isFirstLaunching: $isFirstLaunching, storeModel: storeModel)
}
else {
mainView
}
}
}
```
기존의 온보딩에서 가게이름을 입력하고 버튼을 눌렀을 시에 키보드가 밀리면서 다음페이지로 넘어갔는데 그 오류를 수정했습니다.
```
struct OnboardingStore: View {
//@EnvironmentObject var appstorageManager: AppstorageManager
//Core Data 저장을 위해 가지고 나가기
@Binding var cafeName : String
@ObservedObject var onboardingRouter = OnboardingRouter.shared
@State private var isActive: Bool = false
var body: some View {
VStack(spacing: 0) {
OnboardingCustomHeader(action: {onboardingRouter.previousPage()})
ContentArea {
VStack(alignment:.leading,spacing: 40){
VStack(alignment:.leading, spacing: 12) {
Text("매장의 이름을 알려주세요") …
```
> [Refactor] 온보딩 구조 변경

- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/MainView.swift
```재생성 함수 CoreData 연동```
```재성성 함수 성능 개선```
> [Fix/#83] Improving GPT results performance

- PostKit/PostKit/Model/StoreModel.swift
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
- PostKit/PostKit/View/Setting/SettingToneView.swift
- PostKit/PostKit/View/Setting/SettingView.swift
#94 
Binding값을 배열로 변경하고 값이 3개인지 확인하고 톤을 선택하는 함수를 추가했습니다.
```
// MARK: Extension: Function
extension SelectTone {
private func addTone(tone: String) {
if !selectedTones.contains(tone) {
if selectedTones.count >= 3 {
selectedTones.removeFirst()
selectedTones.append(tone)
}
else {
selectedTones.append(tone)
}
}
}
}
```
```
Binding을 바꾸니 무수히 많은 오류가.. 
코어데이터 형식을 바꿔야 제대로 기능이 완성되는 것 같아서 일단 전부 주석처리하고 TODO로 바꿔야하는 부분 표시해두었습니다~
```
> [Feat] 톤 다중선택 기능 추가

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/Error/ErrorView.swift
- PostKit/PostKit/View/MainView.swift
#96 
뷰를 모듈화 하여 한 곳에 모든 코드를 적지 않고 밑에 extension화 하였습니다.
메인뷰에 많은 모듈이 있으니 읽기 어려우시면 말씀해주세요
```
private var mainHistoryView: some View {
ContentArea {
VStack(alignment: .leading, spacing: 20) {
VStack(alignment: .leading, spacing: 8) {
Text("히스토리")
.font(.title1())
.foregroundColor(Color.gray6)
Text("히스토리를 탭하면 내용이 복사됩니다.")
.font(.body2Bold())
.foregroundColor(Color.gray4)
}
VStack(alignment: .leading, spacing: 20) {
historyIndicator
TabView(selection: $historySelected) {
feedHistory
.tag("피드 글")
hashtagHistory
.tag("해시태그")
}
.tabViewStyle(.page(indexDisplayMode: .never))
}
}
}
}
```
📸 스크린샷(선택)
텝뷰 같은 경우에는 한 파일에 extension으로 관리하는게 맞을지 아니면 다른 파일에서 관리할지 고민입니다.
햅틱 반응과 복사기능은  ㅎㅎ. 내일 와서 할게여~
> [Design] - 탭뷰 구조화

- PostKit/PostKit/Model/NavigationModel.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/MainView.swift
close #102 
> hashtagHistoryDetail이라는 함수를 생성해서 해시태그 히스토리 뷰를 구현했습니다.
```swift
private func hashtagHistoryDetail(date : Date, hashtagContent : String) -> some View {
RoundedRectangle(cornerRadius: radius1)
.frame(height: 160)
.foregroundColor(Color.gray1)
.overlay(alignment: .leading) {
VStack(alignment: .leading, spacing: 8) {
Text(date, style: .date)
.font(.body2Bold())
.foregroundColor(Color.gray4)
Text(hashtagContent)
.font(.body2Bold())
.foregroundColor(Color.gray5)
}
.padding(EdgeInsets(top: 24, leading: 16, bottom: 24, trailing: 16))
}
}
```
```
```
> [Feat] - 해시태그 히스토리 뷰 구현

- PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
- PostKit/PostKit/Protocol/MainViewProtocol.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
- PostKit/PostKit/View/Setting/SettingToneView.swift
- PostKit/PostKit/View/Setting/SettingView.swift
```Onboarding View 저장 함수 오류 수정```
```MainView 함수 간편화```
```Setting뷰에 들어갈때 튕기는 버그 수정```
```CoreData의 큰 변경이 있었습니다. 자잘한 오류가 생길 수 있으니 발견되면 알려주세요.```
|기능|스크린샷|
> [Data] - Onboarding, MainView CoreData func 수정

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/Model/CaptionModel.swift
- PostKit/PostKit/Protocol/MainViewProtocol.swift
- PostKit/PostKit/View/MainView.swift
```Caption Model 추가```
```Caption Protocol 추가```
``` MainView feedHistory가 함수형으로 작성되어있어 ForEach문을 사용하는데 어려움이 있습니다. 구조체로 변경해야할것 같습니다.```
```
> [Data] - Caption Model, Protocol 추가

- PostKit/PostKit/Model/CaptionModel.swift
- PostKit/PostKit/View/MainView.swift
```결과 CoreData 연결```
```Fetch문, 리퀘스트 등등 오류가 많았지만 해결했다!```
|기능|스크린샷|
> [Data/#108] captionResultView CoreData 연동

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/CoreData.xcdatamodeld/CoreData.xcdatamodel/contents
- PostKit/PostKit/Model/HashtagModel.swift
- PostKit/PostKit/Protocol/CaptionResultProtocol.swift
- PostKit/PostKit/Protocol/HashtagProtocol.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/MainView.swift
``` HashtagView fetch 함수```
```HashtagResultView save 함수```
```Hashtag Protocol 파일```
> [Data/#113] Hashtag CoreData 작업

- PostKit/PostKit/Protocol/MainViewProtocol.swift
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/MainView.swift
#113
```메인뷰에서 Hashtag결과 출력```
|기능|스크린샷|
> [Data/#113] 메인뷰에서 Hashtag결과 출력

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/ViewModel/ChatGptService.swift
- PostKit/PostKit/ViewModel/ResponseError.swift
#70 
``` swift
catch {
print("error: \(error)")
// MARK: - Chat Gpt 에러 처리
if error._code == NSURLErrorTimedOut {
print("Time Out Error 발생")
return chatGptResponse(choices: [chatGptChoice(message: chatGptMessage(role: .system, content: "TIMEOUT"))])
}
else if error as! ResponseError == ResponseError.noResponse {
print("Nil Response Error 발생")
return chatGptResponse(choices: [chatGptChoice(message: chatGptMessage(role: .system, content: "NILError"))])
}
else {
print("error: \(error)")
print("Server Error 발생")
return chatGptResponse(choices: [chatGptChoice(message: chatGptMessage(role: .system, content: "ServerError"))])
}
}
```
Error 세부 수정은 해시태그 생성 기능 구현 이후 이어서 진행하겠습니다.
> [Feat] Error 처리

- PostKit/PostKit/Protocol/MainViewProtocol.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/MainView.swift
```결과뷰 한글로 변경```
```날짜 형식 변경```
```지금 GPT가 생성, 재생성시 빈번하게 NIL오류가 뜨는 버그가 있습니다.```
|기능|스크린샷|
> [Fix/#122] 결과뷰 한글로 변경, 날짜 형식 변경

- PostKit/PostKit/Protocol/CaptionResultProtocol.swift
- PostKit/PostKit/View/Caption/CaptionResultView.swift
```스토리 수정 저장을 위해 변수 추가```
```수정뷰가 나오면 Protocol 작성 예정```
> [Data/#137] 히스토리 수정 저장을 위해 변수 추가, 수정뷰가 나오면 Protocol 작성 예정

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Hashtag/HashtagPopover.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
closed #140 
> 클릭 시 위치를 받아서 popover을 띄웠습니다.
```swift
private func handlePopoverClick(location: CGPoint, clickType: PopOverType) {
switch clickType {
case .region:
regionPopoverOffsetFromTop = location.y
case .keyword:
keywordPopoverOffsetFromTop = location.y
}
popupState = clickType
withAnimation(.easeInOut){
isShowingDescription.toggle()
}
DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
withAnimation(.easeInOut) {
isShowingDescription = false
}
}
}
@ViewBuilder
func popoverView(_ type: PopOverType) -> some View {
VStack {
HStack {
Spacer()
VStack(spacing: 0) {
HStack {
Spacer()
TriangleView()
.foregroundColor(.gray1)
.frame(width: 18, height: 12)
.offset(x: 10, y: 3)
}
ZStack {
RoundedRectangle(cornerRadius: radius1)
.frame(width: 200, height: 167)
.foregroundColor(.gray1) …
```
> [Design] - Popover 구현

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit.xcworkspace/xcshareddata/swiftpm/Package.resolved
- PostKit/PostKit/AppDelegate.swift
- PostKit/PostKit/PostKitApp.swift
closed #144 
Delegate 파일을 생성해서 mixpanel을 연결했습니다.
```swift
class AppDelegate: NSObject, UIApplicationDelegate {
func application(
_ application: UIApplication,
didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
) -> Bool {
// ...
Mixpanel.initialize(token: Constants.MixpanelToken, trackAutomaticEvents: true)
Mixpanel.mainInstance().track(event: "Signed Up", properties: [
"Signup Type" : "Referral",
])
return true
}
}
초대는 내일 해드리겠습니다. constants파일이 업데이트 되었으니 노션에서 고쳐주세요!
> [feat] - 믹스패널 연걸

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/ViewModel/CoinManager.swift
- PostKit/PostKit/ViewModel/CoinManger.swift
closed #134 
coinManger파일을 통해 크래딧을 관리합니다. 지금은 테스트때문에 170으로 바꿨지만 배포할때는 24시간으로 바꿀 예정입니다!
```swift
import Foundation
import Combine
import SwiftUI
class CoinManger: ObservableObject {
@AppStorage("coin") var coin: Int = 0
private var cancellable: AnyCancellable?
static let shared = CoinManger()
init() {
cancellable = Timer.publish(every: 170, on: .main, in: .default)
.autoconnect()
.sink { [weak self] _ in
self?.coin = 0
}
}
func coinUse() {
coin += 1
}
}
```
챗 지피티가 안되는게 가장 큰문제라 빨리 해결해야할 것 같아요..
그 외에는 뷰모델 화는 리펙토링떄 해야할 것 같아요 ㅠㅠ
> [Feat] - 크레딧 기능 추가 5회 부터 생성 가능

- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/ViewModel/DailyViewModel.swift
- PostKit/PostKit/ViewModel/MenuViewModel.swift
closed #152 
private 변수들을 함수의 매개변수로 전달하도록 변경
``` swift
func sendMessage(coffeeSelected: Array<String>, dessertSelected: Array<String>, drinkSelected: Array<String>, menuName: String){
```
> [Fix] - Change state variation to private variation

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Component/KeywordAppend.swift
- PostKit/PostKit/View/Component/SelectTextLength.swift
- PostKit/PostKit/ViewModel/CoinManager.swift
closed #154
커스텀 라디오 버튼 제작
```swift
import SwiftUI
struct SelectTextLength: View {
@Binding var selected: Int
let items: [String] = ["짧음","중간","긺"]
var body: some View {
RoundedRectangle(cornerRadius: radius1)
.stroke(Color.gray2)
.foregroundColor(Color.white)
.frame(maxWidth: .infinity)
.frame(height: 94)
.overlay(alignment: .leading) {
VStack(alignment: .leading, spacing: 16) {
Text("글 길이")
.font(.body1Bold())
.foregroundColor(.gray5)
HStack(spacing: 0) {
ForEach(Array(items.enumerated()), id: \.offset) { idx, item in
RaidioBtn(title: item, id: idx,selectedId: self.$selected)
Spacer()
}
}
}
.padding(.all,20)
}
}
}
extension SelectTextLength {
private func radioGroupCallback(id: Int) {
selected = id
}
}
struct RaidioBtn: View {
let id: Int
let title: String
@Binding var selectedId: Int …
```
> [Design/#154] - DailyView, MenuView 2번째 로우파이 적용

- PostKit/PostKit/Protocol/MainViewProtocol.swift
- PostKit/PostKit/View/MainView.swift
```deleteCaptionData 함수 완성```
```deleteCaptionData 함수 최적화```
```생각보다 삭제 기능이 어렵습니다.```
```Fetch를 진행하면서 UUID가 같으면 fetchRequest에서 삭제 조치하도록 작성했습니다.```
```Nil로 처리된 값은 UUID 생성이 되지 않기 때문에 삭제가 되지 않습니다.```
|기능|스크린샷|
[GIF]<img src = "![Uploading RPReplay_Final1698915339.gif…]" width="250">
> [Data] MainView 결과뷰에서 삭제하고 싶은 Caption을 누르면 삭제

- PostKit/PostKit/View/Component/HistoryButton.swift
> [Fix] 오타 긴급 패치

- PostKit/PostKit/Protocol/CaptionResultProtocol.swift
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
#147
```Caption 수정시 수정된 Caption이 저장되도록 함수 작성```
```결과 수정뷰에서 바뀌었는지 확인하기 위한 변수가 추가되었습니다.```
```현재 뷰에서는 긴글이나 좋아요가 제대로 저장되는지 확인하기 어렵습니다.```
> [Data] Caption 수정시 수정된 Caption이 저장되도록 함수 작성

- PostKit/PostKit/Model/NavigationModel.swift
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Error/ErrorView.swift
- PostKit/PostKit/View/MainView.swift
- PostKit/PostKit/ViewModel/DailyViewModel.swift
- PostKit/PostKit/ViewModel/MenuViewModel.swift
closed #176 
``` swift 
if error._code == 10 {
pathManager.path.append(.ErrorResultFailed)
}
else if error._code == 13 {
pathManager.path.append(.ErrorNetwork)
}
```
> [Feat] - Chat Gpt API 오류 처리

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Error/ErrorView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
- PostKit/PostKit/ViewModel/ChatGptViewModel.swift
- PostKit/PostKit/ViewModel/DailyViewModel.swift
- PostKit/PostKit/ViewModel/ErrorViewModel.swift
- PostKit/PostKit/ViewModel/Extension/StringExtension.swift
- PostKit/PostKit/ViewModel/MenuViewModel.swift
closed #194 
``` swift
extension CaptionResultView {
// MARK: - Chat GPT API에 재생성 요청
func regenerateAnswer() { /* Daily, Menu를 선택하지 않아도 이전 답변을 참고하여 재생성 합니다.*/
let chatGptService = ChatGptService()
Task{
self.messages.append(Message(id: UUID(), role: .system, content:viewModel.basicPrompt))
self.messages.append(Message(id: UUID(), role: .user, content: viewModel.prompt))
chatGptService.sendMessage(messages: self.messages)
.sink(
receiveCompletion: { completion in
switch completion {
case .failure(let error):
if error._code == 10 {
pathManager.path.append(.ErrorResultFailed)
}
else if error._code == 13 {
pathManager.path.append(.ErrorNetwork)
}
case .finished:
coinManager.coinUse()
pathManager.path.append(.CaptionResult)
}
},
receiveValue:  { response in
guard let textResponse = …
```
> [Feat] - Gpt prompt 다듬기 & ChatGpt ViewModel 리팩토링

- PostKit/PostKit/Assets.xcassets/Colors/tertiary.colorset/Contents.json
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/Setting/SettingToneView.swift
closed #196
``` swift
Button {
action()
} label: {
HStack{
VStack(alignment: .leading, spacing: 8) {
HStack(spacing: 8) {
Text(concept)
.body1Bold(textColor: selectedTones.contains(concept) ? Color.gray5 : Color.gray4)
if isBest {
Text("BEST")
.body2Bold(textColor: .main)
.padding(.vertical, 2)
.padding(.horizontal, 6)
.background(Color.tertiary)
.clipShape(RoundedRectangle(cornerRadius: 4))
}
}
Text(conceptExample)
.body2Bold(textColor: .gray4)
}
Spacer()
}
.frame(maxWidth: .infinity)
.padding(.all, 20)
.background(selectedTones.contains(concept) ? Color.sub : Color.gray1)
.cornerRadius(radius1)
.background(RoundedRectangle(cornerRadius: radius1).stroke(selectedTones.contains(concept) ? Color.main : Color.gray1, lineWidth: 2))
}
```
> [QA] SelectToneView detail 수정

- PostKit/PostKit/View/Component/CTABtn.swift
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
closed #198 
```swift
extension SelectTone {
private func addTone(tone: String) {
if !selectedTones.contains(tone) && selectedTones.count < 3 {
selectedTones.append(tone)
}
else if selectedTones.contains(tone) {
selectedTones.removeAll(where: {$0 == tone})
}
else {
//TODO: ALERT창 완성되면 ALERT창 적용예정입니다.
}
}
}
```
> [Fix/#198] 버튼 한번 더 누를시 취소, 이름 빈칸시 버튼 비활성화

- PostKit/PostKit/Model/AppStorageManager.swift
- PostKit/PostKit/View/MainViews/MainCaptionView.swift
- PostKit/PostKit/View/MainViews/MainView.swift
- PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
- PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
- PostKit/PostKit/View/Setting/SettingStoreView.swift
- PostKit/PostKit/View/Setting/SettingView.swift
> [QA] Onboarding View QA 진행

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Component/KeywordModal.swift
- PostKit/PostKit/View/Error/ErrorView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/LoadingView.swift
- PostKit/PostKit/View/MainViews/MainCaptionView.swift
- PostKit/PostKit/ViewModel/MixPanelManger.swift
closed #198 
```swift
import SwiftUI
import Mixpanel
struct LoadingView: View {
@EnvironmentObject var pathManager: PathManager
var body: some View {
VStack {
ProgressView()
.controlSize(.large)
.padding(.bottom, 40)
Text("카피가 만들어지고 있어요")
.title1(textColor: .gray6)
.padding(.bottom, 12)
Text("30초 가량 소요될 수 있어요.")
.body2Bold(textColor: .gray4)
}
.onAppear {
if pathManager.path.contains(.Daily) {
Mixpanel.mainInstance().time(event: "일상 글 로딩")
}
else if pathManager.path.contains(.Menu) {
Mixpanel.mainInstance().time(event: "메뉴 글 로딩")
}
else if pathManager.path.contains(.Hashtag) {
Mixpanel.mainInstance().time(event: "해시태그 글 로딩")
}
}
.onDisappear {
if pathManager.path.contains(.Daily) {
Mixpanel.mainInstance().track(event: "일상 글 로딩")
}
else if pathManager.path.contains(.Menu) { …
```
> [Feat/#198] 믹스패널 기능 추가

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/MainViews/MainCaptionView.swift
- PostKit/PostKit/ViewModel/CaptionResultViewModel.swift
- PostKit/PostKit/ViewModel/CoinManager.swift
- PostKit/PostKit/ViewModel/DailyViewModel.swift
- PostKit/PostKit/ViewModel/ErrorViewModel.swift
- PostKit/PostKit/ViewModel/MenuViewModel.swift
closed #212 
``` swift
@AppStorage("coin") var coin: Int = 10
@AppStorage("date") var date: String = "0000.00.00"
static let minimalCoin: Int = 0
static let maximalCoin: Int = 10
private var cancellable: AnyCancellable?
static let shared = CoinManager()
init() {
coin = 10
}
func coinCaptionUse() {
coin -= 2
}
func coinHashtagUse() {
coin -= 1
}
```
> [Feat] - 코인 로직 구현

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
- PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
> Revert "[Fix/#201] OnBoardingView에서 뒤로 돌아갈때 어플이 멈추는 버그 수정"

- PostKit/PostKit/View/Onboarding/OnboardingFinal.swift
- PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
- PostKit/PostKit/View/Onboarding/OnboardingStore.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
- PostKit/PostKit/View/Onboarding/OnboardingView.swift
> [Fix/#201] Fix onboardingview error

- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/ViewModel/CoinManager.swift
> [Fix] Fix variation name

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/AppDelegate.swift
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Component/KeywordModal.swift
- PostKit/PostKit/View/Error/ErrorView.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/Loading/LoadingView.swift
- PostKit/PostKit/View/MainViews/MainCaptionView.swift
- PostKit/PostKit/View/MainViews/MainView.swift
closed #219 
믹스패널 관련 수정 사항을 반영하였습니다. 변경된 이벤트로 테스트가 필요합니다.
> [Feat/#219] 믹스패널 프로퍼티 수정

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Component/CustomHashtag.swift
- PostKit/PostKit/View/Component/KeywordAppend.swift
- PostKit/PostKit/View/Component/KeywordModal.swift
- PostKit/PostKit/View/Component/SelectTextLength.swift
- PostKit/PostKit/View/Onboarding/OnboardingTone.swift
> [QA] 일상 글 생성 뷰 QA 진행

- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Component/CTABtn.swift
- PostKit/PostKit/View/Component/CustomAlertMessage.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/MainViews/MainHistoryView.swift
> [Fix/#214] 엄청난 여정이였다

- PostKit/PostKit/View/Caption/DailyView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
#185
```직접 추가한 변수가 로딩뷰에 나오지 않는 버그 수정```
> [Fix/#185] 직접 추가한 변수가 로딩뷰에 나오지 않는 버그 수정

- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
- PostKit/PostKit/View/Hashtag/HashtagResultView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/MainViews/MainHistoryView.swift
```해쉬태그 로딩뷰```
```수정시 다중 저장 버그 수정```
> [Fix] 해쉬태그 로딩뷰, 해시태그 수정시 다중 저장 버그 수정

- PostKit/PostKit/View/MainViews/MainView.swift
- PostKit/PostKit/ViewModel/CloudKitUserModel.swift
```Cloud 연동 삭제``` 
``` 버전 +1``` 
``` Gpt 키값 변경```
> [Fix/#235] Cloud 연동 삭제, 버전 +1, Gpt 키값 변경

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/MenuView.swift
- PostKit/PostKit/View/Component/KeywordModal.swift
> [Fix/#259] 6,7번뷰 QA

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Caption/CaptionResultView.swift
- PostKit/PostKit/View/Caption/ResultUpdateModalView.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
> [Fix/#262] 8,10번뷰 QA

- PostKit/PostKit.xcodeproj/project.pbxproj
- PostKit/PostKit/View/Component/HistoryEmpty.swift
- PostKit/PostKit/View/Component/SelectTone.swift
- PostKit/PostKit/View/Hashtag/HashtagView.swift
- PostKit/PostKit/View/MainViews/MainHistoryView.swift
- PostKit/PostKit/View/Onboarding/OnboardingIntro.swift
- PostKit/PostKit/View/Setting/SettingToneView.swift
> [Fix] 2차 QA 수정 - 1
